server:
  port : 8081
spring:
  datasource:
   url: jdbc:postgresql://localhost:5432/usermicroservice
   username: postgres
   password: password
  jpa:
   properties:
    hibernate:
     dialect: org.hibernate.dialect.PostgreSQLDialect
     ddl-auto: update
    show-sql: true
